#!/usr/bin/env python
# encoding: utf-8

"""
BIOL7800 Assignment 10 Task 2

Amie Settlecowski
1 Mar. 2016

This program identifies the 10 most common words and the number of occurrences
from text read in from a file using Counter and prints the word and their
counts in descending order
"""
from collections import Counter


def process_string(string):
    '''
    Change every character to lowercase and retain only alphabetic characters
    '''
    string = string.lower()
    string = string.replace("\n", " ")
    new_string = ''
    for character in string:
        if character.isalpha() or character == ' ':
            new_string += character
        else:
            pass
    return new_string


def count_words(string_list):
    '''
    Uses Counter to generates a list, word_counter, of list pairs of the 10
    most common words and their count
    '''
    word_counter = Counter(string_list).most_common(10)
    return word_counter


def print_word_rank(word_counter):
    '''
    Prints words and their counts stored in word_counter
    '''
    for index in word_counter:
        print(index[0], '\t', index[1])


def main():
    # check that task1.txt opens in read mode w/out error
    with open("task1.txt", 'r') as ifile:
        if ifile.readable() == 'False':
            ifile.close()
        else:
            pass

        # read in task_1.txt as one long string
        file_as_string = ifile.read()
        file_as_string = process_string(file_as_string)
        # transform long string into list of every word as separate string
        every_word = file_as_string.split(' ')
        # generate list of lists pairs of 10 most common words and their counts
        word_counter = count_words(every_word)
        # print the pairs of words and their counts in descending order
        print_word_rank(word_counter)

        ifile.close()

if __name__ == '__main__':
    main()
